#!/usr/bin/env python3
"""Interactive, secret-safe setup for the portable Codex relay."""

from __future__ import annotations

import argparse
import getpass
import hashlib
import os
import re
import secrets
import shutil
import subprocess
from pathlib import Path

from app import _default_state_dir


def _prompt_choice(value: str | None) -> str:
    choice = (value or input("Platform [telegram/discord/both]: ")).strip().lower()
    if choice not in {"telegram", "discord", "both"}:
        raise SystemExit("Choose telegram, discord, or both.")
    return choice


def _secret(label: str) -> str:
    value = getpass.getpass(label).strip()
    if not value or "\n" in value or "\r" in value:
        raise SystemExit(f"{label.rstrip(': ')} is required.")
    return value


def _env_line(name: str, value: str | Path) -> str:
    text = str(value)
    if "\n" in text or "\r" in text:
        raise SystemExit(f"Invalid newline in {name}.")
    return f"{name}={text}"


def main() -> int:
    parser = argparse.ArgumentParser(description="Configure Codex Relay")
    parser.add_argument("--platform", choices=("telegram", "discord", "both"))
    parser.add_argument("--env-file", type=Path, default=Path(".env"))
    parser.add_argument("--project-root", type=Path)
    parser.add_argument("--force", action="store_true", help="replace an existing env file")
    args = parser.parse_args()

    codex = shutil.which("codex")
    if not codex:
        raise SystemExit("Codex CLI was not found on PATH. Install Codex CLI first, then run `codex login`.")
    login = subprocess.run(
        [codex, "login", "status"],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        timeout=20,
        check=False,
    )
    if login.returncode != 0:
        raise SystemExit("Codex CLI is not signed in. Run `codex login` and repeat setup.")

    platform = _prompt_choice(args.platform)
    telegram_token: str | None = None
    discord_token: str | None = None
    if platform in {"telegram", "both"}:
        telegram_token = _secret("Telegram bot token: ")
        if not re.fullmatch(r"[0-9]+:[A-Za-z0-9_-]{20,}", telegram_token):
            raise SystemExit("The Telegram bot token format is invalid.")
    if platform in {"discord", "both"}:
        discord_token = _secret("Discord bot token: ")

    default_root = Path.cwd().parent if (Path.cwd() / ".git").exists() else Path.cwd()
    if args.project_root is None:
        entered = input(f"Folder containing your Git projects [{default_root}]: ").strip()
        project_root = Path(entered).expanduser() if entered else default_root
    else:
        project_root = args.project_root.expanduser()
    project_root = project_root.resolve()
    if not project_root.is_dir():
        raise SystemExit(f"Project folder does not exist: {project_root}")

    env_file = args.env_file.expanduser().resolve()
    if env_file.exists() and not args.force:
        raise SystemExit(f"Refusing to overwrite {env_file}. Re-run with --force if intended.")

    pair_code = secrets.token_urlsafe(9)
    pair_hash = hashlib.sha256(pair_code.encode("utf-8")).hexdigest()
    state_dir = _default_state_dir().resolve()
    state_dir.mkdir(parents=True, exist_ok=True, mode=0o700)
    lines = [
        "# Generated by setup_relay.py. Keep this file private and out of Git.",
        _env_line("BOT_PAIR_CODE_SHA256", pair_hash),
        _env_line("CODEX_PROJECT_ROOT", project_root),
        _env_line("BOT_STATE_FILE", state_dir / "state.json"),
        _env_line("CODEX_ARTIFACT_ROOT", state_dir / "artifacts"),
        _env_line("CODEX_BINARY", codex),
    ]
    if telegram_token:
        lines.append(_env_line("TELEGRAM_BOT_TOKEN", telegram_token))
    if discord_token:
        lines.append(_env_line("DISCORD_BOT_TOKEN", discord_token))
    lines.extend(
        [
            "CODEX_TIMEOUT_SECONDS=3600",
            "CODEX_MAX_CONCURRENT_SESSIONS=5",
            "LOG_LEVEL=INFO",
            "",
        ]
    )

    env_file.parent.mkdir(parents=True, exist_ok=True)
    flags = os.O_WRONLY | os.O_CREAT | os.O_TRUNC
    descriptor = os.open(env_file, flags, 0o600)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
            descriptor = -1
            handle.write("\n".join(lines))
    finally:
        if descriptor >= 0:
            os.close(descriptor)
    try:
        os.chmod(env_file, 0o600)
    except OSError:
        pass

    print(f"Configuration written to {env_file}")
    print(f"Pairing code (shown once): {pair_code}")
    if platform in {"telegram", "both"}:
        print("Telegram pairing: send `/pair <code>` in a private message.")
    if platform in {"discord", "both"}:
        print("Discord pairing: send `!pair <code>` in a private message.")
    print(f"Start with: codex-relay --env-file {env_file}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
